version : '3'
services:
  bot: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: alexbot:dev
    networks:
      - bot-network
    depends_on:
      - postgre

  postgre: 
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${password}
    networks:
      - bot-network

networks:
  bot-network:
